packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: 19.1.0
  react-dom: 19.1.0
  next: 15.5.2
  typescript: ^5.7.2
  '@types/react': ^19.0.2
  '@types/react-dom': ^19.0.2
  '@types/node': ^22.10.2
  tailwindcss: ^3.4.17
  autoprefixer: ^10.4.20
  postcss: ^8.5.2
  eslint: ^9.17.0
  eslint-config-next: 15.5.2
  '@supabase/supabase-js': ^2.47.10
  framer-motion: ^11.15.0
  lucide-react: ^0.469.0
  zod: ^3.24.1
  tailwind-merge: ^2.5.5
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^4.1.0
  'jose': ^5.9.6
  '@radix-ui/react-slot': ^1.1.1
  '@radix-ui/react-dialog': ^1.1.4
  '@radix-ui/react-dropdown-menu': ^2.1.4
  '@radix-ui/react-avatar': ^1.1.1
  '@radix-ui/react-badge': ^1.1.1
  '@radix-ui/react-scroll-area': ^1.2.2
  '@radix-ui/react-separator': ^1.1.1
  '@radix-ui/react-tabs': ^1.1.2
  '@radix-ui/react-tooltip': ^1.1.7
